### ISSUE TITLE
Installation on Debian Ubuntu 

### ISSUE THREAD

**Issue by RottenRonnie** [wrybread/weewx-ArduinoWeatherStation#1]
The installation of the zip file failed. Here is the cli output:
`
$ sudo wee_extension --install weewx-aws.zip
[sudo] password for ron:
Request to install 'weewx-aws.zip'
Extracting from zip archive weewx-aws.zip
Traceback (most recent call last):
  File "/usr/bin/wee_extension", line 83, in <module>
    main()
  File "/usr/bin/wee_extension", line 75, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 107, in install_extension
    self.tmpdir, self.logger)
  File "/usr/share/weewx/weecfg/__init__.py", line 1258, in extract_zip
    zip_archive = zipfile.ZipFile(open(filename, mode='r'))
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
`

**Comment by Mrstraub** [comment]
I had the same problem. It took me a lot of time to find the error, but the solution is quite simple. You have to download the zip file. Currently a .git file is being downloaded and renamed to weewx-aws.zip.

Try this:
1) Download the driver:
wget -O weewx-aws.zip https://github.com/wrybread/weewx-ArduinoWeatherStation/archive/master.zip

2) Install the driver:
sudo wee_extension --install weewx-aws.zip

**Comment by wrybread** [comment]
Interesting. Is that an issue with github, or with how I uploaded the package to github?

**Comment by openbooknoobdeveloper** [comment]
@RottenRonnie @Mrstraub do you guys could install in the end? could you guys help me setup my weather station? thank you.
